# vim: filetype=ruby
# if you type "brew bundle --global", homebrew uses .Brewfile

tap "universal-ctags/universal-ctags"
tap "oven-sh/bun"
tap "delphinus/sfmono-square"

brew "gnupg"
brew "rbenv"
brew "ruby-build"
brew "tig"
brew "rg"
brew "neovim"
brew "jq"
brew "shellcheck"
brew "universal-ctags"
brew "git"
brew "fzf"
brew "ssh-copy-id"
brew "eza"
brew "fd"
brew "bat"
brew "git-delta"
brew "webp"
brew "tidy-html5"
brew "difftastic"
brew "bun"
brew "sfmono-square"

# brew "ansible"
# brew "ansible-lint"
# brew "colima"
# brew "goenv"
# brew "maven"
# brew "mono"
# brew "nvm"
# brew "pandoc"
# brew "sbt"
# brew "scala"
# brew "yamllint"

# brew "mysql" use docker image instead
# brew "postgresql" use docker image instead
# brew "jsonlint" # use "npm install -g jsonlint" instead
