# vim: set ft=zsh :

# zprofile is loaded only when zsh is run as login shell


# brew path
export PATH=/opt/homebrew/bin:/usr/local/sbin:$PATH

JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null)
if [[ -n $JAVA_HOME ]]; then
	export JAVA_HOME
fi

# rbenv
if type rbenv >/dev/null 2>&1; then
	eval "$(rbenv init -)"
fi

# pyenv
if type pyenv >/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi

# goenv & golang
if type goenv >/dev/null 2>&1; then
	eval "$(goenv init -)"

elif type go 1>/dev/null 2>&1; then
	export GOPATH=$HOME/.go
	export PATH=$PATH:$GOPATH/bin
fi

# user path
export PATH=~/apps/bin:$PATH

# for svn and git editor
export EDITOR=vim

# The next line updates PATH for the Google Cloud SDK.
if [[ -f "${HOME}/google-cloud-sdk/path.zsh.inc" ]]; then
	. "${HOME}/google-cloud-sdk/path.zsh.inc";
fi

# The next line enables shell command completion for gcloud.
if [[ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]]; then
	. "${HOME}/google-cloud-sdk/completion.zsh.inc";
fi


# node manager
if [[ -d $HOME/.volta ]]; then
	# use volta instead of nvm
	export VOLTA_HOME="$HOME/.volta"
	export PATH="$VOLTA_HOME/bin:$PATH"

elif [[ -f ~/.nvm/nvm.sh ]]; then
	# installed manually
	export NVM_DIR="$HOME/.nvm"
	source ~/.nvm/nvm.sh

elif [[ -f /usr/local/opt/nvm/nvm.sh ]]; then
	# installed by homebrew (x86 mac)
	if [[ ! -d $HOME/.nvm ]]; then
		mkdir $HOME/.nvm
	fi
	export NVM_DIR="$HOME/.nvm"
	source /usr/local/opt/nvm/nvm.sh

elif [[ -f /opt/homebrew/opt/nvm/nvm.sh ]]; then
	# installed by homebrew (arm64 mac)
	if [[ ! -d $HOME/.nvm ]]; then
		mkdir $HOME/.nvm
	fi
	export NVM_DIR="$HOME/.nvm"
	source /opt/homebrew/opt/nvm/nvm.sh
fi


# npm
if type npm 1>/dev/null 2>&1; then
	if [[ ! -f ~/.npm_completion ]]; then
		npm completion > ~/.npm_completion
	fi
	source ~/.npm_completion
fi


# next, zshrc is loaded
