# vim: set ft=zsh :

# zprofile is loaded only when zsh is run as login shell

JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null)
if [[ -n $JAVA_HOME ]]; then
	export JAVA_HOME
fi

# rbenv
if type rbenv >/dev/null 2>&1; then
	eval "$(rbenv init -)"
fi

# pyenv
if type pyenv >/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi

# golang
if type go 1>/dev/null 2>/dev/null; then
	export GOPATH=$HOME/go
	export PATH=$PATH:$GOPATH/bin
fi

# brew path
export PATH=/usr/local/sbin:$PATH

# user path
export PATH=~/apps/bin:$PATH

# for svn and git editor
export EDITOR=vim

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [[ -f "${HOME}/google-cloud-sdk/path.zsh.inc" ]]; then
	. "${HOME}/google-cloud-sdk/path.zsh.inc";
fi

# The next line enables shell command completion for gcloud.
if [[ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]]; then
	. "${HOME}/google-cloud-sdk/completion.zsh.inc";
fi

# nvm
export NVM_DIR="$HOME/.nvm"

if [[ -f ~/.nvm/nvm.sh ]]; then
	# installed manually
	source ~/.nvm/nvm.sh

elif [[ -f /usr/local/opt/nvm/nvm.sh ]]; then
	# installed by homebrew
	if [[ ! -d $HOME/.nvm ]]; then
		mkdir $HOME/.nvm
	fi
	source /usr/local/opt/nvm/nvm.sh
fi

# npm
if type npm 1>/dev/null 2>&1; then
	if [[ ! -f ~/.npm_completion ]]; then
		npm completion > ~/.npm_completion
	fi
	source ~/.npm_completion
fi

# load local zprofile
if [ -f ~/.zprofile_local ]; then
	source ~/.zprofile_local
fi

# next, zshrc is loaded
