# vim: set ft=zsh :
# zprofile is loaded only when zsh is run as login shell

# brew path
export PATH=/opt/homebrew/bin:$PATH

# user path
export PATH=~/.dotfiles/bin:~/.local/bin:$PATH

# for git editor
export EDITOR=nvim

# java home for macos
if [[ $OSTYPE == darwin* ]]; then
	JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null)
	if [[ -n $JAVA_HOME ]]; then
		export JAVA_HOME
	fi
fi

# node manager
if [[ -d $HOME/.volta ]]; then
	: "nothing to do, volta writes path to .zshenv"

elif [[ -f /opt/homebrew/opt/nvm/nvm.sh ]]; then
	export NVM_DIR="$HOME/.nvm"
fi

# load local zprofile if exists
if [[ -f ~/.zprofile.local ]]; then
	source ~/.zprofile.local
fi

