# vim: set ft=zsh :

# zshrc is loaded in interactive mode.

# basic aliases
alias here="open ."
alias home="open ~/"
alias edit="open -a CotEditor"
alias al="ag --pager 'less -R'"
alias gmail="open -na 'Google Chrome' --args --app='https://mail.google.com/mail/u/0/#inbox'"
alias bash="HISTFILE=${HOME}/.bash_history /bin/bash"
alias reload="exec ${SHELL}"
alias preview="open -a 'Preview'"
alias acl="/bin/ls -lhGe"

# prompt setting
case "${OSTYPE}" in
	darwin*)
		if [[ ${LC_TERMINAL} == iTerm2 ]] || [[ ${TERM_PROGRAM} == vscode ]] || [[ ${TERMINAL_EMULATOR} == *JediTerm ]]; then
			X_PROMPT="%{[1;36m%}%3~%{[m%}"
		else
			X_PROMPT="%{[0;32m%}${USER}@${HOST%%.*}%{[m%}:%{[0;34m%}%3~%{[m%}"
		fi
		;;
	linux*)
		X_PROMPT="%{[0;35m%}${USER}@${HOST%%.*}%{[m%}:%{[0;34m%}%1~%{[m%}"
		;;
esac

function zle-line-init zle-keymap-select {
	case $KEYMAP in
		main|viins)
			PROMPT="${X_PROMPT} %{[0;36m%}i%{[m%}%(!.#.$) "
			;;
		vicmd)
			PROMPT="${X_PROMPT} %{[0;31m%}n%{[m%}%(!.#.$) "
			;;
		vivis|vivli)
			PROMPT="${X_PROMPT} %{[0;31m%}v%{[m%}%(!.#.$) "
			;;
	esac
	zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# history
HISTFILE=${HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt EXTENDED_HISTORY
setopt noflowcontrol

# zsh binding style
bindkey -v

# zsh history searching
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey '' history-beginning-search-backward-end
bindkey '' history-beginning-search-forward-end
bindkey -a '' vi-beginning-of-line
bindkey -v '' vi-beginning-of-line
bindkey -a '' vi-end-of-line
bindkey -v '' vi-end-of-line
bindkey -a '' history-incremental-search-backward
bindkey -v '' history-incremental-search-backward
bindkey -a '' history-incremental-search-forward
bindkey -v '' history-incremental-search-forward

# fix keys
bindkey '[H' beginning-of-line # home
bindkey '[F' end-of-line # end
bindkey '[5~' beginning-of-history # page up
bindkey '[6~' end-of-history # page down


# script alias
alias -s rb="ruby"
alias -s js="node"
alias -s {txt,md,html,css,scss}="edit"
alias -s {jpg,jpeg,png,gif,webp}="preview"

# beep
setopt no_hist_beep
setopt no_list_beep

# cd extention
setopt auto_cd
setopt auto_pushd
DIRSTACKSIZE=2

cdpath=(~ ../ $cdpath)


# addtion path for completion
if [[ -d ~/.zsh/completion ]]; then
	fpath=(~/.zsh/completion $fpath)
fi

# zsh completion
autoload -U compinit
compinit

zstyle ':completion:*:default' menu selection
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list _history
zstyle ':completion:*:messages' format "%{[1;33m%}%d %{[m%}"
zstyle ':completion:*:warnings' format "%{[1;31m%}No matches for: %d %{[m%}"
zstyle ':completion:*:descriptions' format "%{[1;34m%}%d %{[m%}"
zstyle ':completion:*:corrections' format "%{[1;33m%}%d %{[1;31m%}(errors: %e)%b %{[m%}"
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*' group-name ''


# alias another basic command
if type eza 1>/dev/null 2>&1; then
	alias ls=" eza --time-style=iso"
	alias ll="ls -glF --time-style=long-iso"
	alias la="ls -a"
	alias lla="ls -aglF --time-style=long-iso"
else
	alias ls=" ls -G"
	alias ll="ls -lF"
	alias la="ls -A"
	alias lla="ls -AlF"
fi

if type bat 1>/dev/null 2>&1; then
	alias cat="bat --theme=Dracula"
fi

# settings for java
if [[ -n $JAVA_HOME ]]; then
	alias javac="javac -J-Dfile.encoding=UTF-8"
	alias java="java -Dfile.encoding=UTF-8"
fi

# nvim
if type nvim 1>/dev/null 2>&1; then
	alias vi=nvim
	alias view="nvim -R"
	alias vimdiff="nvim -d"
fi

# git
alias git-vimdiff="git difftool --tool=vimdiff --no-prompt"

autoload -Uz vcs_info

setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{yellow}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{red}+"
zstyle ':vcs_info:*' formats "%F{green}%c%u[%b]%f"
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () {
	vcs_info
	RPROMPT='${vcs_info_msg_0_}'
	setopt transient_rprompt
}

# -- dev command
source ~/.dotfiles/zsh/dev

# -- launchctl utilities
source ~/.dotfiles/zsh/launchctl

# -- fuctions
source ~/.dotfiles/zsh/functions

if [[ $LC_TERMINAL == iTerm2 ]]; then
	# change bg color on ssh login
	if [[ -x ~/apps/bin/ssh-bg ]]; then
		alias ssh=ssh-bg
		compdef ssh-bg=ssh
	fi

	test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

if [[ $OSTYPE == darwin* ]]; then
	# make
	if [[ -x ~/apps/bin/make-notify ]]; then
		alias make=make-notify
		compdef make-notify=make
	fi
fi

if [[ -f .zshrc.local ]]; then
	source .zshrc.local
fi

