#!/bin/zsh

if ! type fzf 1>/dev/null 2>&1; then
	echo "[ERROR] peco is not installed. type 'brew install peco'"
	return 1
fi

if [ -z "$1" ]; then
	return 1
fi

# https://developer.apple.com/library/mac/documentation/Carbon/Conceptual/SpotlightQuery/Concepts/QueryFormat.html
local MD_QUERY="kMDItemContentType == 'public.folder' && kMDItemFSName == '$1*'"

local RESULT=$(mdfind -onlyin ~ "$MD_QUERY" | fzf)

if [ -z "$RESULT" ]; then
	return 1
fi

echo $RESULT
cd $RESULT

