#!/bin/zsh

function google() {
	if [[ ${#*} -eq 0 ]]; then return 1; fi
  Q=$(node -p -e 'process.argv.slice(1).map(q => encodeURIComponent(q)).join("+")' "$@")
  #Q=$(echo "$*" | nkf -WwMQ | tr = %)
	#Q=$(echo "${(j/%20/)*}")
	open "https://www.google.com/search?q=$Q"
}
