#!/bin/zsh

# jq + less
if ! type jq 1>/dev/null 2>&1; then
	echo "[ERROR] jq is not installed. type 'brew install jq'"
	return 1
fi

local QUERY
local FILE

if [ -p /dev/stdin ]; then
	# pipe: cat hoge.json | jl .
	if [ $# -eq 0 ]; then
		QUERY="."
	else
		QUERY="$1"
	fi
	FILE="-"
elif [ -t 0 ]; then
	# file: jl . hoge.json
	if [ $# -eq 1 ]; then
		QUERY="."
		FILE=$1
	elif [ $# -eq 2 ]; then
		QUERY="$1"
		FILE="$2"
	else
		return 1
	fi
else
	# redirect stdin: jl . <hoge.json
	if [ $# -eq 0 ]; then
		QUERY="."
	else
		QUERY="$1"
	fi
	FILE="-"
fi

jq "$QUERY" -C 2>&1 $FILE | less -R

