#!/bin/zsh

function launchctl-start() {
	if ! isInstalled fzf; then
		{
			echo "fzf not found"
			echo "type 'brew install fzf'"
		} >&2
		return 1
	fi

	local SERVICE_NAME=$(launchctl list | grep "^-" | fzf | head -n 1 | cut -f 3)

	if [ -n "$SERVICE_NAME" ]; then
		echo "Start ${SERVICE_NAME}"
		launchctl start $SERVICE_NAME
	else
		return 1
	fi
}

function launchctl-stop() {
	if ! isInstalled fzf; then
		{
			echo "fzf not found"
			echo "type 'brew install fzf'"
		} >&2
		return 1
	fi

	local SERVICE_NAME=$(launchctl list | grep -v "^-" | fzf | head -n 1 | cut -f 3)

	if [ -n "$SERVICE_NAME" ]; then
		echo "Stop ${SERVICE_NAME}"
		launchctl stop $SERVICE_NAME
	else
		return 1
	fi
}

