on:
  push:
    branches:
      - actions_test

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get-commit-hash
        id: commit_hash
        run: |
          value=$(git rev-parse HEAD)
          echo "value=$value" >> $GITHUB_OUTPUT
    outputs:
      text: ${{ steps.commit_hash.outputs.value }}

  hello:
    needs: message
    uses: ./.github/workflows/reusable-echo.yml
    with:
      message: "HEAD is ${{ needs.message.outputs.text }}"
